sudo: required

services:
  - docker

before_install:
  - docker build -t tricm/docker-react -f Dockerfile.dev .

script:
  - docker run tricm/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'my-docker-react'
  env: 'MyDockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-684076731558'
  bucket_path: 'my-docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
